### ISSUE TITLE
Looking for the code that works in the Tutorials.

### ISSUE THREAD

**Issue by martinws** [XaeroDegreaz/SmartSocket#2]
Hi 

I've been looking at this SmartSocket code linked directly from the Website SmartSocket website. It looks just like the thing I've been looking for. I'm thinking of creating a SmartSocket client for iOS/Objective C. Problem is I've found the tutorial discusses methods which are not present in the in the v2.0 source code or JavaDocs. e.g. addDataListener and addEventListener.

There could be more (Event enum?). I'm downloading directly from https://github.com/XaeroDegreaz/SmartSocket/downloads. Should I be downloading from elsewhere?

**Comment by XaeroDegreaz** [comment]
addDataListener is part of the Flash API, and is not included in the JavaDoc (it's embedded in the ActionScript code for the Flash API).

Nope, you're downloading from the right place :)

**Comment by martinws** [comment]
Ok.. I saw the use of a 'SmartSocketClient' in the demo and thought the Java one would work the same. (I have no Flash experience).
